# Generated by Django 4.1.4 on 2023-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shortdesc',
            field=models.TextField(null=True),
        ),
    ]
