# Generated by Django 4.1.4 on 2023-01-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_shortdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shortdesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
