# Generated by Django 4.1.5 on 2023-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-03 15:13:16.417631'),
            preserve_default=False,
        ),
    ]
