# Generated by Django 4.1.4 on 2023-01-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Postlar'},
        ),
    ]
